[package]
name = "nn-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tty-interface = "4.0.0"
micrograd-rs = "0.0.2"
